# Demonstração de uso da API com balanceador e instâncias
# Execute este script no diretório do projeto após iniciar os containers.

Write-Host '1) Inicie os containers (em outro terminal):'
Write-Host '   docker compose up --build'
Write-Host ''
Write-Host '2) Criar um registro de exemplo:'
Write-Host '   curl -X POST http://localhost:8080/records -H "Content-Type: application/json" -d "{\"name\": \"Maria Silva\", \"type\": \"matricula\", \"detail\": \"Engenharia de Software\"}"'
Write-Host ''
Write-Host '3) Listar registros:'
Write-Host '   curl http://localhost:8080/records'
Write-Host ''
Write-Host '4) Verificar saúde e métricas:'
Write-Host '   curl http://localhost:8080/health'
Write-Host '   curl http://localhost:8080/metrics'
Write-Host ''
Write-Host '5) Mostrar instância que respondeu (observe o header x-instance-id):'
Write-Host '   curl -i http://localhost:8080/records'
Write-Host ''
Write-Host '6) Simular falha de app1 e continuar usando a API:'
Write-Host '   docker compose stop app1'
Write-Host '   curl http://localhost:8080/records'
Write-Host ''
Write-Host '7) Voltar a ligar app1:'
Write-Host '   docker compose start app1'
